when:
  - event: push
    branch: main

steps:
  - name: build-and-push
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: registry.mocalabs.dev/mocalabs/blog
      registry: https://registry.mocalabs.dev
      username: abby
      password: ${REGISTRY_PASSWORD}
      tags:
        - latest
        - ${CI_COMMIT_SHA}
      dockerfile: Dockerfile
      insecure: false
      debug: true
      verbose: true
